package:
  name: jopy
  version: "0.0.1"

#source:
#  fn: CoolProp-5.1.0.tar.gz
#  url: https://pypi.python.org/packages/source/C/CoolProp/CoolProp-5.1.0.tar.gz
#  md5: aeeb1fa4d667761e5a4260850bf045d6

#source:
#  git_rev: master
#  git_url: https://github.com/coolprop/coolprop.git

#  patches:
   # List any patch files here
   # - fix.patch

# build:
  # noarch_python: True
  # preserve_egg_dir: True
  # entry_points:
    # Put any entry points (scripts to be generated automatically) here. The
    # syntax is module:function.  For example
    #
    # - coolprop = coolprop:main
    #
    # Would create an entry point called coolprop that calls coolprop.main()


  # If this is a new build for the same version, increment the build
  # number. If you do not include this key, it defaults to 0.
  # number: 1

requirements:
  build:
    - python
    - setuptools

  run:
    - python

#test:
  # Python imports
  #imports:
  #  - jopy

  # commands:
    # You can put test commands to be run here.  Use this to test that the
    # entry points work.


  # You can also put a file called run_test.py in the recipe that will be run
  # at test time.

  # requires:
    # Put any additional test requirements here.  For example
    # - nose

about:
  home: http://www.jorrit.org
  license: MIT License

# See
# http://docs.continuum.io/conda/build.html for
# more information about meta.yaml
