# 2015-07-23 14:05 CAUTION: This file is automatically generated from builder.py, do not edit it manually
__author__ = 'Jorrit Wronski'
__email__ = 'jopy@jorrit.org'
__version__ = '0.0.1'

# Fix matplotlib backend on X-less machines 
import os, matplotlib
if "DISPLAY" not in os.environ: matplotlib.use('Agg')

# Add more import here is you like 