# 2015-07-16 18:01 CAUTION: This file is automatically generated from D:\Documents\Python\jopy.win.git\dev\builder.py, do not edit it manually
__author__ = 'Jorrit Wronski'
__email__ = 'jopy@jorrit.org'
__version__ = '0.0.1'
