# 2015-07-23 14:05 CAUTION: This file is automatically generated from dev\builder.py, do not edit it manually
from __future__ import print_function

__author__ = 'Jorrit Wronski'
__email__ = 'jopy@jorrit.org'
__version__ = '0.0.1'

# Fix matplotlib backend on X-less machines
try: 
	import matplotlib
	USE_MATPLOTLIB=True
except Exception as e:
	print(str(e))
	print("Disabling matplotlib functions.")
	USE_MATPLOTLIB=False
	
if USE_MATPLOTLIB:
	import os
	if "DISPLAY" not in os.environ: 
		matplotlib.use('Agg')
		USE_DISPLAY=False
	else:
		USE_DISPLAY=True
else:
	USE_DISPLAY=False

# Add more imports here is you like 